### PR TITLE
Add buffer number to label

### PR DESCRIPTION
**Pull request by nicoe**
Once I have a lot of buffers I often use the buffer number to switch quickly from one to another.
This PR adds the buffer number to the label

### CODE REVIEW

**Comment by pacha** [comment]
@nicoe Thanks for the PR! I think that the idea makes a lot of sense. I would rather have this feature as an option for the user though. If you can add a configuration variable we can merge it. If not, I can take a look as soon as I have a moment. In any case, thanks again :+1:

**Comment by nicoe** [comment]
* Andrés Sopeña [2019-07-10 22:44:34]:
> @nicoe Thanks for the PR! I think that the idea makes a lot of
> sense. I would rather have this feature as an option for the user
> though. If you can add a configuration variable we can merge it. If
> not, I can take a look as soon as I have a moment. In any case,
> thanks again :+1: 

Thanks for the appreciation :).
I'll take into account your proposition of making it an option. I'll
try to work on it this week-end.

**Comment by nicoe** [comment]
I updated the PR in cas you didn't receive the notification :smile:

**Comment by pacha** [comment]
Hi @nicoe, yep I totally missed it! I'll take a look at it!

**Comment by pacha** [comment]
Hi there @nicoe. Sorry for the time it took for your PR to be merged. I refactored the code to support your functionality and the one requested in #8. Take a look at `vem-tabline-selecting-buffers` in the [ help file](https://raw.githubusercontent.com/pacha/vem-tabline/master/doc/tabline.txt) to see how to configure it. Thanks for your PR!

**Comment by nicoe** [comment]
Thanks a lot !
I think there's a typo in autoload/vem_tabline/buffers.vim as you compare with 'bufnr' and not 'buffnr' (but it could be the other way around :stuck_out_tongue_closed_eyes:).

**Comment by pacha** [comment]
@nicoe. Damn, true! Fixed :sweat_smile:

**Pull request merged**
